### ISSUE TITLE
Question: How do we switch on the toggles under the Experiments section of the Game Settings?

### ISSUE THREAD

**Issue by ndtreviv** [cubeworx/mcbe-server#13]
I've added some addons that require some of the Experiments toggles to be switched on (eg: https://www.curseforge.com/minecraft/mc-addons/hihiirokane-addon-ii-for-bedrock-edition requires:

* Holiday Creator Features
* Creation of Custom Biomes and
* Additional Modding Capabilities

I can't work out how to switch these on using the environment variables. They seem to be world specific. Is there a way to get a world where they are switched on, or where we can switch them on using the console interface?

**Comment by claflico** [comment]
I don't believe that "Experiments" is supported in the server version directly. When searching I came across this [article](https://support.aternos.org/hc/en-us/articles/4407553257873-Enabling-experimental-gameplay-Minecraft-Bedrock-Edition-) that recommends creating the world locally with Experiments enabled and then uploading it to the server.

**Comment by ndtreviv** [comment]
Yes, I've read a few like that, and worked out that it's world-specific.
Unfortunately we only have the Minecraft client on the Switch, which is effectively a closed box. There's no way to get data off of it without doing some serious hackery, which apparently Nintendo are now automatically identifying and banning your device 🙁

Can I ask a big favour? Do you think you could create a template world with the switches enabled that I could download and use?! I'd be very grateful!
Alternatively I'm going to have to analyse the world dat file in hexfiend or similar and try to work out where the switches are set, which may take a while!

Thanks for getting back to me on it, and Happy New Year!

**Comment by ndtreviv** [comment]
FYI I also found this: https://bugs.mojang.com/browse/BDS-3265
According to the [Level format](https://minecraft.fandom.com/wiki/Bedrock_Edition_level_format) the values are bytes. I might try fiddling with a few values to see what I can do.

**Comment by ndtreviv** [comment]
Nevermind, I got hold of a world from somewhere else. In case you want to use it, I can confirm that it comes with the experimental features all switched on:
[World.zip](https://github.com/cubeworx/mcbe-server/files/7996306/World.zip)
