### ISSUE TITLE
Can't get addons to work.

### ISSUE THREAD

**Issue by ForceConstant** [cubeworx/mcbe-server#9]
I see that the addons.sh script is working fine, as I see the packs getting installed in the worlds, and the json files created, but when I connect to the server, the addons don't show up as activated. Any ideas? Any way to enable debug on server to see more information?

**Comment by claflico** [comment]
What addons are you trying to use? Links if possible. 

Some of the addons I've tested with required certain commands be ran from the console in order to activate them so that might be the issue. The addon documentation usually indicates if this is the case.

I've not yet found any way to increase the log level unfortunately and the content log file doesn't have much useful info in it.

**Comment by ndtreviv** [comment]
I've downloaded and installed mods and addons from curseforge

for example: https://www.curseforge.com/minecraft/mc-addons/more-weapons-be

I can see in the logs that they're being unzipped and added, eg:
```
Checking for .mcaddon, .mcpack, or .zip files in /mcbe/data/addons.
Unzipping /mcbe/data/addons/Nuke_addon_(resources).mcpack
Unzipping /mcbe/data/addons/SuperCreepers.mcpack
Creating directory /mcbe/data/addons/behavior_packs
Unzipping /mcbe/data/addons/Minecraft_More_Weapons_0.1.zip
Unzipping /mcbe/data/addons/superheroes_v1.zip
Checking /mcbe/data/addons for behavior_packs.
Creating /mcbe/data/worlds/Bedrock-Level/world_behavior_packs.json
Creating symlink /mcbe/server/behavior_packs/92446d0d-92ba-4c3e-af84-51549b681f2c to /mcbe/data/addons/behavior_packs/92446d0d-92ba-4c3e-af84-51549b681f2c/
Adding Super Creepers uuid & version to /mcbe/data/worlds/Bedrock-Level/world_behavior_packs.json
Checking /mcbe/data/addons for resource_packs.
Starting Minecraft Bedrock Server Version 1.18.2.03 with the following configuration:
########## SERVER PROPERTIES ##########
allow-cheats=false
compression-threshold=1
content-log-file-enabled=false
correct-player-movement=false
default-player-permission-level=member
difficulty=normal
force-gamemode=false
gamemode=survival
level-name=Bedrock-Level
level-seed=
max-players=10
max-threads=8
online-mode=true
player-idle-timeout=30
player-movement-action-direction-threshold=0.85
player-movement-distance-threshold=0.3
player-movement-duration-threshold-in-ms=500
player-movement-score-threshold=20
server-authoritative-block-breaking=false
server-authoritative-movement=server-auth
server-name=CubeWorx-MCBE
server-port=19132
server-portv6=19133
texturepack-required=false
tick-distance=4
view-distance=32
white-list=false
```

But there are no new weapons in the inventory (Nintendo Switch)... 🤔 Maybe I'm missing some action that I need to do first?

**Comment by ndtreviv** [comment]
Interestingly this resource pack worked: https://www.curseforge.com/minecraft/mc-addons/compliance-64x-bedrock

**Comment by ndtreviv** [comment]
Ok, Super Creepers definitely worked as well :D Turns out it's just the addon that doesn't work, then...
